# Simple test, that checks, if `pip install .` installs all nessesary dependencies to execute
# `ci_sdr.pt.ci_sdr(...)`

name: Run python dependency test

on: 
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # Print cmd before executing
        trap 'echo -e "$ $BASH_COMMAND"' DEBUG
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        # torch CPU installs faster, hence manual install
        pip install torch --index-url https://download.pytorch.org/whl/cpu
        pip install .
    - name: Test with pytest
      run: |
        pytest tests/test_burn.py
      env:
        OMP_NUM_THREADS: 1
        MKL_NUM_THREADS: 1
